project:
  type: website
  output-dir: docs

website:
  title: "S.L. Carter"
  favicon: www/hex-logo.png
  navbar:
    logo: www/hex-logo.png 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://github.com/Steven314
        icon: github
        text: Steven314
        target: _blank
    tools:
      - icon: code-slash
        menu:
          - text: Source Code
            href:  https://github.com/Steven314/Steven314.github.io
          - text: Report a Bug
            href:  https://github.com/Steven314/Steven314.github.io/issues
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



