project:
  type: website
  output-dir: docs

website:
  title: "S. L. Carter"
  favicon: www/hex-logo.png
  navbar:
    logo: www/hex-logo.png
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - text: About
        menu:
          - books.qmd
          - tech.qmd
    right:
      - href: https://github.com/Steven314
        icon: github
        target: _blank
      - href: https://www.linkedin.com/in/steven-carter-77b391271/
        icon: linkedin
        target: _blank
    tools:
      - icon: code-slash
        menu:
          - text: Source Code
            href:  https://github.com/Steven314/Steven314.github.io
          - text: Report a Bug
            href:  https://github.com/Steven314/Steven314.github.io/issues
  page-footer:
    background: light
    left: |
      <span>{{< fa brands creative-commons >}} 2025 Steven L. Carter<br></span>
      <span>All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/).<br>
      View the source at [{{< fa brands github >}} GitHub]({{<https://github.com/Steven314/Steven314.github.io>}}).

format:
  html:
    theme:
      light: [lux, custom_light.scss]
      dark:  [lux, custom_dark.scss]
    css: styles.css
    toc: true
    toc-location: left
